version: "3.8"

services:
  app:
    build: ./
    container_name: listing_service_app_silali
    networks:
      - app-network
    volumes:
      - ./:/listing-service
    ports:
      - "8080:8080"
    expose:
      - 8080
  database:
    container_name: listing_service_db_silali
    image: postgres:16.1
    restart: always
    networks:
      - app-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=listing_service
    ports:
      - '5442:5432'
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 10s
      retries: 2


volumes:
  db:
    driver: local

networks:
  app-network:
    driver: bridge